import { Space_Mono } from 'next/font/google'
import './globals.css'

import localFont from 'next/font/local'

export const recoleta = localFont({ src: '../../public/fonts/recoleta.ttf' })

const space = Space_Mono({ subsets: ['latin'], weight: ['400', '700'] })

// export const metadata = {
//   title: 'BrandIn',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>BrandIn</title>
        <meta name='description' content='Description' />
      </head>
      <body className={space.className}>{children}</body>
    </html>
  )
}
